export const RECENT_MESSAGE_LIMIT = 18
export const INITIAL_HISTORY_LIMIT = 40
export const MEMORY_INJECTION_LIMIT = 12
export const MEMORY_EXTRACTION_LIMIT = 2
export const MESSAGE_FEEDBACK_INJECTION_LIMIT = 8
export const CONVERSATION_SUMMARY_MAX_LENGTH = 1600
