/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDialog: typeof import('./src/components/ui/alert-dialog/AlertDialog.vue')['default']
    AlertDialogAction: typeof import('./src/components/ui/alert-dialog/AlertDialogAction.vue')['default']
    AlertDialogCancel: typeof import('./src/components/ui/alert-dialog/AlertDialogCancel.vue')['default']
    AlertDialogContent: typeof import('./src/components/ui/alert-dialog/AlertDialogContent.vue')['default']
    AlertDialogDescription: typeof import('./src/components/ui/alert-dialog/AlertDialogDescription.vue')['default']
    AlertDialogFooter: typeof import('./src/components/ui/alert-dialog/AlertDialogFooter.vue')['default']
    AlertDialogHeader: typeof import('./src/components/ui/alert-dialog/AlertDialogHeader.vue')['default']
    AlertDialogMedia: typeof import('./src/components/ui/alert-dialog/AlertDialogMedia.vue')['default']
    AlertDialogTitle: typeof import('./src/components/ui/alert-dialog/AlertDialogTitle.vue')['default']
    AlertDialogTrigger: typeof import('./src/components/ui/alert-dialog/AlertDialogTrigger.vue')['default']
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    ChatErrorCard: typeof import('./src/components/ChatErrorCard.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatLoading: typeof import('./src/components/ChatLoading.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatMessageList: typeof import('./src/components/ChatMessageList.vue')['default']
    ChatPage: typeof import('./src/components/ChatPage.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    Dialog: typeof import('./src/components/ui/dialog/Dialog.vue')['default']
    DialogClose: typeof import('./src/components/ui/dialog/DialogClose.vue')['default']
    DialogContent: typeof import('./src/components/ui/dialog/DialogContent.vue')['default']
    DialogDescription: typeof import('./src/components/ui/dialog/DialogDescription.vue')['default']
    DialogFooter: typeof import('./src/components/ui/dialog/DialogFooter.vue')['default']
    DialogHeader: typeof import('./src/components/ui/dialog/DialogHeader.vue')['default']
    DialogOverlay: typeof import('./src/components/ui/dialog/DialogOverlay.vue')['default']
    DialogScrollContent: typeof import('./src/components/ui/dialog/DialogScrollContent.vue')['default']
    DialogTitle: typeof import('./src/components/ui/dialog/DialogTitle.vue')['default']
    DialogTrigger: typeof import('./src/components/ui/dialog/DialogTrigger.vue')['default']
    EditKbDialog: typeof import('./src/components/EditKbDialog.vue')['default']
    EmptySession: typeof import('./src/components/EmptySession.vue')['default']
    Field: typeof import('./src/components/ui/field/Field.vue')['default']
    FieldContent: typeof import('./src/components/ui/field/FieldContent.vue')['default']
    FieldDescription: typeof import('./src/components/ui/field/FieldDescription.vue')['default']
    FieldError: typeof import('./src/components/ui/field/FieldError.vue')['default']
    FieldGroup: typeof import('./src/components/ui/field/FieldGroup.vue')['default']
    FieldLabel: typeof import('./src/components/ui/field/FieldLabel.vue')['default']
    FieldLegend: typeof import('./src/components/ui/field/FieldLegend.vue')['default']
    FieldSeparator: typeof import('./src/components/ui/field/FieldSeparator.vue')['default']
    FieldSet: typeof import('./src/components/ui/field/FieldSet.vue')['default']
    FieldTitle: typeof import('./src/components/ui/field/FieldTitle.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    HistoryPage: typeof import('./src/components/HistoryPage.vue')['default']
    InlineRename: typeof import('./src/components/InlineRename.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    KbMentionDropdown: typeof import('./src/components/KbMentionDropdown.vue')['default']
    KbMentionPill: typeof import('./src/components/KbMentionPill.vue')['default']
    KnowledgeBasePage: typeof import('./src/components/KnowledgeBasePage.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    MarkdownRender: typeof import('./src/components/MarkdownRender.vue')['default']
    ModelSelector: typeof import('./src/components/ModelSelector.vue')['default']
    MoveCopyDialog: typeof import('./src/components/MoveCopyDialog.vue')['default']
    RecycleBinPage: typeof import('./src/components/RecycleBinPage.vue')['default']
    Separator: typeof import('./src/components/ui/separator/Separator.vue')['default']
    SettingsPage: typeof import('./src/components/SettingsPage.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SplashScreen: typeof import('./src/components/SplashScreen.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
    Textarea: typeof import('./src/components/ui/textarea/Textarea.vue')['default']
  }
}
