/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChatErrorCard: typeof import('./src/components/ChatErrorCard.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatLoading: typeof import('./src/components/ChatLoading.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ChatMessageList: typeof import('./src/components/ChatMessageList.vue')['default']
    ChatPage: typeof import('./src/components/ChatPage.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    EditKbDialog: typeof import('./src/components/EditKbDialog.vue')['default']
    EmptySession: typeof import('./src/components/EmptySession.vue')['default']
    FileExplorer: typeof import('./src/components/FileExplorer.vue')['default']
    HistoryPage: typeof import('./src/components/HistoryPage.vue')['default']
    InlineRename: typeof import('./src/components/InlineRename.vue')['default']
    KbMentionDropdown: typeof import('./src/components/KbMentionDropdown.vue')['default']
    KbMentionPill: typeof import('./src/components/KbMentionPill.vue')['default']
    KnowledgeBasePage: typeof import('./src/components/KnowledgeBasePage.vue')['default']
    MarkdownRender: typeof import('./src/components/MarkdownRender.vue')['default']
    ModelSelector: typeof import('./src/components/ModelSelector.vue')['default']
    MoveCopyDialog: typeof import('./src/components/MoveCopyDialog.vue')['default']
    RecycleBinPage: typeof import('./src/components/RecycleBinPage.vue')['default']
    SettingsPage: typeof import('./src/components/SettingsPage.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    SplashScreen: typeof import('./src/components/SplashScreen.vue')['default']
    TabBar: typeof import('./src/components/TabBar.vue')['default']
  }
}
