INSERT INTO "permissions" ("id", "code", "name", "description", "type", "resource", "parent_code", "sort_order", "status") VALUES
('perm-dashboard', 'dashboard', '仪表盘', '查看系统仪表盘', 'menu', '/dashboard', NULL, 1, 'active'),
('perm-users', 'users', '用户管理', '管理系统用户', 'menu', '/users', NULL, 2, 'active'),
('perm-users:read', 'users:read', '查看用户', '查看用户列表', 'action', 'users', 'users', 0, 'active'),
('perm-users:create', 'users:create', '创建用户', '创建新用户', 'action', 'users', 'users', 0, 'active'),
('perm-users:update', 'users:update', '编辑用户', '编辑用户信息', 'action', 'users', 'users', 0, 'active'),
('perm-users:delete', 'users:delete', '删除用户', '删除用户', 'action', 'users', 'users', 0, 'active'),
('perm-users:status', 'users:status', '用户状态', '启用/禁用用户', 'action', 'users', 'users', 0, 'active'),
('perm-roles', 'roles', '角色管理', '管理用户角色', 'menu', '/roles', NULL, 3, 'active'),
('perm-roles:read', 'roles:read', '查看角色', '查看角色列表', 'action', 'roles', 'roles', 0, 'active'),
('perm-roles:create', 'roles:create', '创建角色', '创建新角色', 'action', 'roles', 'roles', 0, 'active'),
('perm-roles:update', 'roles:update', '编辑角色', '编辑角色信息', 'action', 'roles', 'roles', 0, 'active'),
('perm-roles:delete', 'roles:delete', '删除角色', '删除角色', 'action', 'roles', 'roles', 0, 'active'),
('perm-rag', 'rag', '知识库管理', '管理知识库和文档', 'menu', '/rag', NULL, 4, 'active'),
('perm-rag:read', 'rag:read', '查看知识库', '查看知识库列表', 'action', 'rag', 'rag', 0, 'active'),
('perm-rag:create', 'rag:create', '创建知识库', '创建新知识库', 'action', 'rag', 'rag', 0, 'active'),
('perm-rag:update', 'rag:update', '编辑知识库', '编辑知识库信息', 'action', 'rag', 'rag', 0, 'active'),
('perm-rag:delete', 'rag:delete', '删除知识库', '删除知识库', 'action', 'rag', 'rag', 0, 'active'),
('perm-sessions', 'sessions', '会话管理', '管理用户会话', 'menu', '/sessions', NULL, 5, 'active'),
('perm-sessions:read', 'sessions:read', '查看会话', '查看会话列表', 'action', 'sessions', 'sessions', 0, 'active'),
('perm-sessions:revoke', 'sessions:revoke', '撤销会话', '撤销用户会话', 'action', 'sessions', 'sessions', 0, 'active'),
('perm-audit', 'audit', '审计日志', '查看系统审计日志', 'menu', '/audit', NULL, 6, 'active'),
('perm-audit:read', 'audit:read', '查看审计日志', '查看审计日志', 'action', 'audit', 'audit', 0, 'active'),
('perm-profile', 'profile', '个人中心', '个人信息和密码修改', 'menu', '/profile', NULL, 7, 'active'),
('perm-profile:read', 'profile:read', '查看个人信息', '查看个人信息', 'action', 'profile', 'profile', 0, 'active'),
('perm-profile:update', 'profile:update', '修改个人信息', '修改个人信息', 'action', 'profile', 'profile', 0, 'active'),
('perm-profile:password', 'profile:password', '修改密码', '修改登录密码', 'action', 'profile', 'profile', 0, 'active'),
('perm-modelProviders', 'modelProviders', '模型管理', '管理AI模型提供商', 'menu', '/modelProviders', NULL, 8, 'active'),
('perm-modelProviders:read', 'modelProviders:read', '查看模型', '查看模型列表', 'action', 'modelProviders', 'modelProviders', 0, 'active'),
('perm-modelProviders:create', 'modelProviders:create', '创建模型', '创建新模型配置', 'action', 'modelProviders', 'modelProviders', 0, 'active'),
('perm-modelProviders:update', 'modelProviders:update', '编辑模型', '编辑模型配置', 'action', 'modelProviders', 'modelProviders', 0, 'active'),
('perm-modelProviders:delete', 'modelProviders:delete', '删除模型', '删除模型配置', 'action', 'modelProviders', 'modelProviders', 0, 'active'),
('perm-moduleSettings', 'moduleSettings', '模块设置', '系统模块配置', 'menu', '/moduleSettings', NULL, 9, 'active'),
('perm-moduleSettings:read', 'moduleSettings:read', '查看设置', '查看模块设置', 'action', 'moduleSettings', 'moduleSettings', 0, 'active'),
('perm-moduleSettings:update', 'moduleSettings:update', '修改设置', '修改模块设置', 'action', 'moduleSettings', 'moduleSettings', 0, 'active')
ON CONFLICT ("code") DO NOTHING;

INSERT INTO "role_permissions" ("id", "role_code", "permission_id", "app") VALUES
('rp-sa-dashboard', 'SUPER_ADMIN', 'perm-dashboard', 'admin'),
('rp-sa-users', 'SUPER_ADMIN', 'perm-users', 'admin'),
('rp-sa-users-read', 'SUPER_ADMIN', 'perm-users:read', 'admin'),
('rp-sa-users-create', 'SUPER_ADMIN', 'perm-users:create', 'admin'),
('rp-sa-users-update', 'SUPER_ADMIN', 'perm-users:update', 'admin'),
('rp-sa-users-delete', 'SUPER_ADMIN', 'perm-users:delete', 'admin'),
('rp-sa-users-status', 'SUPER_ADMIN', 'perm-users:status', 'admin'),
('rp-sa-roles', 'SUPER_ADMIN', 'perm-roles', 'admin'),
('rp-sa-roles-read', 'SUPER_ADMIN', 'perm-roles:read', 'admin'),
('rp-sa-roles-create', 'SUPER_ADMIN', 'perm-roles:create', 'admin'),
('rp-sa-roles-update', 'SUPER_ADMIN', 'perm-roles:update', 'admin'),
('rp-sa-roles-delete', 'SUPER_ADMIN', 'perm-roles:delete', 'admin'),
('rp-sa-rag', 'SUPER_ADMIN', 'perm-rag', 'admin'),
('rp-sa-rag-read', 'SUPER_ADMIN', 'perm-rag:read', 'admin'),
('rp-sa-rag-create', 'SUPER_ADMIN', 'perm-rag:create', 'admin'),
('rp-sa-rag-update', 'SUPER_ADMIN', 'perm-rag:update', 'admin'),
('rp-sa-rag-delete', 'SUPER_ADMIN', 'perm-rag:delete', 'admin'),
('rp-sa-sessions', 'SUPER_ADMIN', 'perm-sessions', 'admin'),
('rp-sa-sessions-read', 'SUPER_ADMIN', 'perm-sessions:read', 'admin'),
('rp-sa-sessions-revoke', 'SUPER_ADMIN', 'perm-sessions:revoke', 'admin'),
('rp-sa-audit', 'SUPER_ADMIN', 'perm-audit', 'admin'),
('rp-sa-audit-read', 'SUPER_ADMIN', 'perm-audit:read', 'admin'),
('rp-sa-profile', 'SUPER_ADMIN', 'perm-profile', 'admin'),
('rp-sa-profile-read', 'SUPER_ADMIN', 'perm-profile:read', 'admin'),
('rp-sa-profile-update', 'SUPER_ADMIN', 'perm-profile:update', 'admin'),
('rp-sa-profile-password', 'SUPER_ADMIN', 'perm-profile:password', 'admin'),
('rp-sa-modelProviders', 'SUPER_ADMIN', 'perm-modelProviders', 'admin'),
('rp-sa-modelProviders-read', 'SUPER_ADMIN', 'perm-modelProviders:read', 'admin'),
('rp-sa-modelProviders-create', 'SUPER_ADMIN', 'perm-modelProviders:create', 'admin'),
('rp-sa-modelProviders-update', 'SUPER_ADMIN', 'perm-modelProviders:update', 'admin'),
('rp-sa-modelProviders-delete', 'SUPER_ADMIN', 'perm-modelProviders:delete', 'admin'),
('rp-sa-moduleSettings', 'SUPER_ADMIN', 'perm-moduleSettings', 'admin'),
('rp-sa-moduleSettings-read', 'SUPER_ADMIN', 'perm-moduleSettings:read', 'admin'),
('rp-sa-moduleSettings-update', 'SUPER_ADMIN', 'perm-moduleSettings:update', 'admin'),
('rp-admin-dashboard', 'ADMIN', 'perm-dashboard', 'admin'),
('rp-admin-users', 'ADMIN', 'perm-users', 'admin'),
('rp-admin-users-read', 'ADMIN', 'perm-users:read', 'admin'),
('rp-admin-users-create', 'ADMIN', 'perm-users:create', 'admin'),
('rp-admin-users-update', 'ADMIN', 'perm-users:update', 'admin'),
('rp-admin-users-status', 'ADMIN', 'perm-users:status', 'admin'),
('rp-admin-roles', 'ADMIN', 'perm-roles', 'admin'),
('rp-admin-roles-read', 'ADMIN', 'perm-roles:read', 'admin'),
('rp-admin-roles-update', 'ADMIN', 'perm-roles:update', 'admin'),
('rp-admin-rag', 'ADMIN', 'perm-rag', 'admin'),
('rp-admin-rag-read', 'ADMIN', 'perm-rag:read', 'admin'),
('rp-admin-rag-create', 'ADMIN', 'perm-rag:create', 'admin'),
('rp-admin-rag-update', 'ADMIN', 'perm-rag:update', 'admin'),
('rp-admin-sessions', 'ADMIN', 'perm-sessions', 'admin'),
('rp-admin-sessions-read', 'ADMIN', 'perm-sessions:read', 'admin'),
('rp-admin-audit', 'ADMIN', 'perm-audit', 'admin'),
('rp-admin-audit-read', 'ADMIN', 'perm-audit:read', 'admin'),
('rp-admin-profile', 'ADMIN', 'perm-profile', 'admin'),
('rp-admin-profile-read', 'ADMIN', 'perm-profile:read', 'admin'),
('rp-admin-profile-update', 'ADMIN', 'perm-profile:update', 'admin'),
('rp-admin-profile-password', 'ADMIN', 'perm-profile:password', 'admin'),
('rp-admin-modelProviders', 'ADMIN', 'perm-modelProviders', 'admin'),
('rp-admin-modelProviders-read', 'ADMIN', 'perm-modelProviders:read', 'admin'),
('rp-admin-modelProviders-update', 'ADMIN', 'perm-modelProviders:update', 'admin'),
('rp-user-dashboard', 'USER', 'perm-dashboard', 'admin'),
('rp-user-profile', 'USER', 'perm-profile', 'admin'),
('rp-user-profile-read', 'USER', 'perm-profile:read', 'admin'),
('rp-user-profile-update', 'USER', 'perm-profile:update', 'admin'),
('rp-user-profile-password', 'USER', 'perm-profile:password', 'admin')
ON CONFLICT ("role_code", "permission_id", "app") DO NOTHING;