/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppRecycleBinRouteImport } from './routes/app/recycle-bin'
import { Route as AppKbRouteImport } from './routes/app/kb'
import { Route as AppHistoryRouteImport } from './routes/app/history'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as AppChatSessionIdRouteImport } from './routes/app/chat/$sessionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRecycleBinRoute = AppRecycleBinRouteImport.update({
  id: '/recycle-bin',
  path: '/recycle-bin',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppKbRoute = AppKbRouteImport.update({
  id: '/kb',
  path: '/kb',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatSessionIdRoute = AppChatSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => AppChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/kb': typeof AppKbRoute
  '/app/recycle-bin': typeof AppRecycleBinRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/kb': typeof AppKbRoute
  '/app/recycle-bin': typeof AppRecycleBinRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/chat': typeof AppChatRouteWithChildren
  '/app/history': typeof AppHistoryRoute
  '/app/kb': typeof AppKbRoute
  '/app/recycle-bin': typeof AppRecycleBinRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/chat/$sessionId': typeof AppChatSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/chat'
    | '/app/history'
    | '/app/kb'
    | '/app/recycle-bin'
    | '/app/settings'
    | '/app/'
    | '/app/chat/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/chat'
    | '/app/history'
    | '/app/kb'
    | '/app/recycle-bin'
    | '/app/settings'
    | '/app'
    | '/app/chat/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/chat'
    | '/app/history'
    | '/app/kb'
    | '/app/recycle-bin'
    | '/app/settings'
    | '/app/'
    | '/app/chat/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/recycle-bin': {
      id: '/app/recycle-bin'
      path: '/recycle-bin'
      fullPath: '/app/recycle-bin'
      preLoaderRoute: typeof AppRecycleBinRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/kb': {
      id: '/app/kb'
      path: '/kb'
      fullPath: '/app/kb'
      preLoaderRoute: typeof AppKbRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat/$sessionId': {
      id: '/app/chat/$sessionId'
      path: '/$sessionId'
      fullPath: '/app/chat/$sessionId'
      preLoaderRoute: typeof AppChatSessionIdRouteImport
      parentRoute: typeof AppChatRoute
    }
  }
}

interface AppChatRouteChildren {
  AppChatSessionIdRoute: typeof AppChatSessionIdRoute
}

const AppChatRouteChildren: AppChatRouteChildren = {
  AppChatSessionIdRoute: AppChatSessionIdRoute,
}

const AppChatRouteWithChildren =
  AppChatRoute._addFileChildren(AppChatRouteChildren)

interface AppRouteRouteChildren {
  AppChatRoute: typeof AppChatRouteWithChildren
  AppHistoryRoute: typeof AppHistoryRoute
  AppKbRoute: typeof AppKbRoute
  AppRecycleBinRoute: typeof AppRecycleBinRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChatRoute: AppChatRouteWithChildren,
  AppHistoryRoute: AppHistoryRoute,
  AppKbRoute: AppKbRoute,
  AppRecycleBinRoute: AppRecycleBinRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
