/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRecycleRouteImport } from './routes/_authenticated/recycle'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedKnowledgeBaseRouteImport } from './routes/_authenticated/knowledgeBase'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedCompanionsRouteImport } from './routes/_authenticated/companions'
import { Route as AuthenticatedChatTabIdRouteImport } from './routes/_authenticated/chat/$tabId'
import { Route as AuthenticatedCompanionsCompanionIdMemoriesRouteImport } from './routes/_authenticated/companions/$companionId.memories'
import { Route as AuthenticatedCompanionsCompanionIdChatRouteImport } from './routes/_authenticated/companions/$companionId.chat'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecycleRoute = AuthenticatedRecycleRouteImport.update({
  id: '/recycle',
  path: '/recycle',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeBaseRoute =
  AuthenticatedKnowledgeBaseRouteImport.update({
    id: '/knowledgeBase',
    path: '/knowledgeBase',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompanionsRoute = AuthenticatedCompanionsRouteImport.update({
  id: '/companions',
  path: '/companions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatTabIdRoute = AuthenticatedChatTabIdRouteImport.update({
  id: '/chat/$tabId',
  path: '/chat/$tabId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompanionsCompanionIdMemoriesRoute =
  AuthenticatedCompanionsCompanionIdMemoriesRouteImport.update({
    id: '/$companionId/memories',
    path: '/$companionId/memories',
    getParentRoute: () => AuthenticatedCompanionsRoute,
  } as any)
const AuthenticatedCompanionsCompanionIdChatRoute =
  AuthenticatedCompanionsCompanionIdChatRouteImport.update({
    id: '/$companionId/chat',
    path: '/$companionId/chat',
    getParentRoute: () => AuthenticatedCompanionsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companions': typeof AuthenticatedCompanionsRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/knowledgeBase': typeof AuthenticatedKnowledgeBaseRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recycle': typeof AuthenticatedRecycleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chat/$tabId': typeof AuthenticatedChatTabIdRoute
  '/companions/$companionId/chat': typeof AuthenticatedCompanionsCompanionIdChatRoute
  '/companions/$companionId/memories': typeof AuthenticatedCompanionsCompanionIdMemoriesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/companions': typeof AuthenticatedCompanionsRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/knowledgeBase': typeof AuthenticatedKnowledgeBaseRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recycle': typeof AuthenticatedRecycleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/chat/$tabId': typeof AuthenticatedChatTabIdRoute
  '/companions/$companionId/chat': typeof AuthenticatedCompanionsCompanionIdChatRoute
  '/companions/$companionId/memories': typeof AuthenticatedCompanionsCompanionIdMemoriesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/companions': typeof AuthenticatedCompanionsRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/knowledgeBase': typeof AuthenticatedKnowledgeBaseRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recycle': typeof AuthenticatedRecycleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/chat/$tabId': typeof AuthenticatedChatTabIdRoute
  '/_authenticated/companions/$companionId/chat': typeof AuthenticatedCompanionsCompanionIdChatRoute
  '/_authenticated/companions/$companionId/memories': typeof AuthenticatedCompanionsCompanionIdMemoriesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/companions'
    | '/history'
    | '/knowledgeBase'
    | '/profile'
    | '/recycle'
    | '/settings'
    | '/chat/$tabId'
    | '/companions/$companionId/chat'
    | '/companions/$companionId/memories'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/companions'
    | '/history'
    | '/knowledgeBase'
    | '/profile'
    | '/recycle'
    | '/settings'
    | '/chat/$tabId'
    | '/companions/$companionId/chat'
    | '/companions/$companionId/memories'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/companions'
    | '/_authenticated/history'
    | '/_authenticated/knowledgeBase'
    | '/_authenticated/profile'
    | '/_authenticated/recycle'
    | '/_authenticated/settings'
    | '/_authenticated/chat/$tabId'
    | '/_authenticated/companions/$companionId/chat'
    | '/_authenticated/companions/$companionId/memories'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recycle': {
      id: '/_authenticated/recycle'
      path: '/recycle'
      fullPath: '/recycle'
      preLoaderRoute: typeof AuthenticatedRecycleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledgeBase': {
      id: '/_authenticated/knowledgeBase'
      path: '/knowledgeBase'
      fullPath: '/knowledgeBase'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companions': {
      id: '/_authenticated/companions'
      path: '/companions'
      fullPath: '/companions'
      preLoaderRoute: typeof AuthenticatedCompanionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$tabId': {
      id: '/_authenticated/chat/$tabId'
      path: '/chat/$tabId'
      fullPath: '/chat/$tabId'
      preLoaderRoute: typeof AuthenticatedChatTabIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companions/$companionId/memories': {
      id: '/_authenticated/companions/$companionId/memories'
      path: '/$companionId/memories'
      fullPath: '/companions/$companionId/memories'
      preLoaderRoute: typeof AuthenticatedCompanionsCompanionIdMemoriesRouteImport
      parentRoute: typeof AuthenticatedCompanionsRoute
    }
    '/_authenticated/companions/$companionId/chat': {
      id: '/_authenticated/companions/$companionId/chat'
      path: '/$companionId/chat'
      fullPath: '/companions/$companionId/chat'
      preLoaderRoute: typeof AuthenticatedCompanionsCompanionIdChatRouteImport
      parentRoute: typeof AuthenticatedCompanionsRoute
    }
  }
}

interface AuthenticatedCompanionsRouteChildren {
  AuthenticatedCompanionsCompanionIdChatRoute: typeof AuthenticatedCompanionsCompanionIdChatRoute
  AuthenticatedCompanionsCompanionIdMemoriesRoute: typeof AuthenticatedCompanionsCompanionIdMemoriesRoute
}

const AuthenticatedCompanionsRouteChildren: AuthenticatedCompanionsRouteChildren =
  {
    AuthenticatedCompanionsCompanionIdChatRoute:
      AuthenticatedCompanionsCompanionIdChatRoute,
    AuthenticatedCompanionsCompanionIdMemoriesRoute:
      AuthenticatedCompanionsCompanionIdMemoriesRoute,
  }

const AuthenticatedCompanionsRouteWithChildren =
  AuthenticatedCompanionsRoute._addFileChildren(
    AuthenticatedCompanionsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCompanionsRoute: typeof AuthenticatedCompanionsRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedKnowledgeBaseRoute: typeof AuthenticatedKnowledgeBaseRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecycleRoute: typeof AuthenticatedRecycleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChatTabIdRoute: typeof AuthenticatedChatTabIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompanionsRoute: AuthenticatedCompanionsRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedKnowledgeBaseRoute: AuthenticatedKnowledgeBaseRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecycleRoute: AuthenticatedRecycleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChatTabIdRoute: AuthenticatedChatTabIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
