export { useOverlayHost } from './host/useOverlayHost'
export { default as OverlayHost } from './host/OverlayHost.vue'
export { openDialog, closeDialog, closeAllDialogs } from './services/dialog.service'
export { openContextMenu, closeContextMenu, closeAllContextMenus } from './services/context-menu.service'
export { defineDialog } from './composables/useDialog'
export { defineContextMenu } from './composables/useContextMenu'
export type { OverlayItem, DialogBaseProps, ContextMenuBaseProps } from './types/overlay.types'
